# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.customize ["modifyvm", :id,
                       "--memory", 512] 

  config.vm.forward_port 80, 8080      # HTTP
end
