#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'jenkins',
  :git => 'file:///Users/tkomiya/work/chef-jenkins',
  :ref => 'allow_using_nginx_package'
cookbook 'nginx'
