#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'jenkins',
  :git => 'https://github.com/opscode-cookbooks/jenkins.git'
cookbook 'runit',
  :git => 'https://github.com/gansbrest/runit.git',
  :ref => 'rpm_rehl_root_dir_fix'
cookbook 'nginx'
