#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'jenkins',
  :git => 'git@github.com:tk0miya/chef-jenkins.git',
  :ref => 'COOK-2754'
cookbook 'runit',
  :git => 'git@github.com:tk0miya/chef-runit.git',
  :ref => 'COOK-2760'
cookbook 'nginx'
