source 'https://rubygems.org'

group :deploy do
  gem 'capistrano'
  gem 'capistrano_colors'
  gem 'capistrano-rbenv', '>= 0.0.11'
  gem 'capistrano-rbenv-ruby193deps-centos5'
  gem 'capistrano-paratrooper-chef',
    :git => 'file:///Users/tkomiya/work/capistrano-paratrooper-chef'
  gem 'rvm-capistrano'
  gem 'rvm-capistrano-ruby193deps-centos',
    :git => 'file:///Users/tkomiya/work/rvm-capistrano-ruby193deps-centos'
  gem 'chef', '>= 11.0.0'
  gem 'librarian-chef'
end
